# Generated by Django 3.0.8 on 2020-07-22 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Designer',
            new_name='Model',
        ),
    ]
